### ISSUE TITLE
Square corners can be seen with this installed

### ISSUE THREAD

**Issue by Kytara56** [mohvn/dropshadow-zenbrowser#4]
I really love this mod, but recently it started to behave strange because now it shows square corners that overlap the padding on the browser,  and it's bugging me off

![Captura de pantalla 2024-10-17 222204](https://github.com/user-attachments/assets/6a1b6ad9-a2b2-4cea-95c7-730f6beeca9f)

**Comment by Anthonyy232** [comment]
Can confirm

**Comment by mohvn** [comment]
> I really love this mod, but recently it started to behave strange because now it shows square corners that overlap the padding on the browser, and it's bugging me off
> 
> ![Captura de pantalla 2024-10-17 222204](https://private-user-images.githubusercontent.com/99623297/377684138-6a1b6ad9-a2b2-4cea-95c7-730f6beeca9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNTE4MDksIm5iZiI6MTcyOTI1MTUwOSwicGF0aCI6Ii85OTYyMzI5Ny8zNzc2ODQxMzgtNmExYjZhZDktYTJiMi00Y2VhLTk1YzctNzMwZjZiZWVjYTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDExMzgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNTFhNDIwOWI1ODliYWQ0YzU1OTc4ZTkyNjRlNDZkYzJhOWQ3OTg2YWEzOWFiODZlMDhjMjQ0MTAxYmZmODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xloDscSYrAKJw4PX6lBa47b91BLbSw1Kx69hoIYQTsE)

Thanks for the heads up. I'll fix this and push out an update in the next version.

**Comment by mohvn** [comment]
> I really love this mod, but recently it started to behave strange because now it shows square corners that overlap the padding on the browser, and it's bugging me off
> 
> ![Captura de pantalla 2024-10-17 222204](https://private-user-images.githubusercontent.com/99623297/377684138-6a1b6ad9-a2b2-4cea-95c7-730f6beeca9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDkxNzksIm5iZiI6MTcyOTUwODg3OSwicGF0aCI6Ii85OTYyMzI5Ny8zNzc2ODQxMzgtNmExYjZhZDktYTJiMi00Y2VhLTk1YzctNzMwZjZiZWVjYTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDExMDc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NzhmYjUwM2VlOTZjMzdmZmFmNjQzOGIyYzgxOTUxMzk2OWNmMTljMjVlNmNhZWJkMzJiNDAxZjY5ZjE0YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-zBW_P2AvUtgjbD-HrzJdAAj1wKH5Av6xeXt_ZJ4B8c)

Fixed in https://github.com/zen-browser/theme-store/pull/607

Update your themes 😁🤙
