### ISSUE TITLE
Rounded corners

### ISSUE THREAD

**Issue by ekrem4rda** [mohvn/dropshadow-zenbrowser#5]
the extension makes a weird black corner 
![Ekran görüntüsü 2024-10-27 142225](https://github.com/user-attachments/assets/fcf3d9ef-08c1-45ee-8246-3a694c7356ca)

**Comment by mohvn** [comment]
![image](https://github.com/user-attachments/assets/bc4d367b-f20b-430f-8f80-c48a5f4f46a4)
fixed on new zen's update v1.0.1-a.14
